import type { Metadata } from "next";
import { headers } from "next/headers";
import { Geist, Geist_Mono } from "next/font/google";
import { SessionProvider } from "@/components/auth/session-context";
import { auth } from "@/lib/auth";
import Navbar from "@/components/Navbar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const dynamic = "force-dynamic";

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const headersList = new Headers(await headers());
  const sessionResult = await auth.api.getSession({ headers: headersList });
  const session = sessionResult?.session ?? null;
  const user = sessionResult?.user ?? null;

  return (
    <html lang="en">
      <head>
        {process.env.NODE_ENV === "development" && (
          <script
            async
            crossOrigin="anonymous"
            src="https://tweakcn.com/live-preview.min.js"
          />
        )}
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider value={{ user, session }}>
          <Navbar />
          {/* Match the navbar’s shell */}
          <main className="site-shell py-6">{children}</main>
        </SessionProvider>
      </body>
    </html>
  );
}
